FROM node:20-alpine

WORKDIR /app

# Установка зависимостей (npm install вместо npm ci из-за bundled deps CKEditor)
COPY package*.json ./
RUN npm install

# Копирование исходного кода
COPY . .

EXPOSE 4205

CMD ["npm", "start"]

