# Generated by Django 5.0.1 on 2025-11-17 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержимое (HTML)')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('view_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('can_delete', models.ManyToManyField(blank=True, related_name='deletable_articles', to=settings.AUTH_USER_MODEL, verbose_name='Могут удалять')),
                ('can_edit', models.ManyToManyField(blank=True, related_name='editable_articles', to=settings.AUTH_USER_MODEL, verbose_name='Могут редактировать')),
                ('can_view', models.ManyToManyField(blank=True, related_name='viewable_articles', to=settings.AUTH_USER_MODEL, verbose_name='Могут просматривать')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='articles/images/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Альтернативный текст')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article', verbose_name='Статья')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Изображение статьи',
                'verbose_name_plural': 'Изображения статей',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое (HTML)')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('version_number', models.IntegerField(verbose_name='Номер версии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('change_description', models.TextField(blank=True, verbose_name='Описание изменений')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='articles.article', verbose_name='Статья')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_versions', to=settings.AUTH_USER_MODEL, verbose_name='Автор версии')),
            ],
            options={
                'verbose_name': 'Версия статьи',
                'verbose_name_plural': 'Версии статей',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='articles_ar_slug_452037_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-updated_at'], name='articles_ar_updated_037d05_idx'),
        ),
        migrations.AddIndex(
            model_name='articleversion',
            index=models.Index(fields=['article', '-version_number'], name='articles_ar_article_1189eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articleversion',
            unique_together={('article', 'version_number')},
        ),
    ]
