# Generated by Django 5.0.1 on 2025-11-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_tag_article_tags'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_slug_452037_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
