# Generated by Django 5.0.1 on 2025-11-20 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_articles_ar_slug_452037_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название опции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Опция статьи',
                'verbose_name_plural': 'Опции статей',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['sort_order', 'name'], name='articles_ar_sort_or_ac4434_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleOptionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='articles.article', verbose_name='Статья')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='articles.articleoption', verbose_name='Опция')),
            ],
            options={
                'verbose_name': 'Значение опции статьи',
                'verbose_name_plural': 'Значения опций статей',
                'ordering': ['option__sort_order', 'option__name'],
                'indexes': [models.Index(fields=['article', 'option'], name='articles_ar_article_59dbb7_idx')],
                'unique_together': {('article', 'option')},
            },
        ),
    ]
