# Generated by Django 5.0.1 on 2025-11-20 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articleoption_articleoptionvalue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('users', models.ManyToManyField(blank=True, related_name='article_groups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Группа пользователей',
                'verbose_name_plural': 'Группы пользователей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_level', models.CharField(choices=[('none', 'Нет доступа'), ('read', 'Только чтение'), ('full', 'Полные права')], default='none', max_length=10, verbose_name='Уровень доступа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='articles.category', verbose_name='Категория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_permissions', to='articles.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Право доступа группы на категорию',
                'verbose_name_plural': 'Права доступа групп на категории',
                'ordering': ['group__name', 'category__name'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='articles_gr_name_b2f49e_idx'),
        ),
        migrations.AddIndex(
            model_name='categorypermission',
            index=models.Index(fields=['group', 'category'], name='articles_ca_group_i_93036c_idx'),
        ),
        migrations.AddIndex(
            model_name='categorypermission',
            index=models.Index(fields=['category', 'permission_level'], name='articles_ca_categor_12861b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorypermission',
            unique_together={('group', 'category')},
        ),
    ]
