# Generated by Django 5.0.1 on 2025-11-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articleattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='articleattachment',
            new_name='articles_ar_article_1d1453_idx',
            old_name='articles_ar_article_7a8b2c_idx',
        ),
    ]
