# Generated by Django 5.0.1 on 2025-12-03 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_rename_articles_ar_article_7a8b2c_idx_articles_ar_article_1d1453_idx'),
    ]

    operations = [
        # Сначала создаем новые модели
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['sort_order', 'name'], name='articles_te_sort_or_f2aa69_idx')],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='articles.technology', verbose_name='Технология')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ['technology', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElementPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_level', models.CharField(choices=[('none', 'Нет доступа'), ('read', 'Только чтение'), ('full', 'Полные права')], default='none', max_length=10, verbose_name='Уровень доступа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='articles.element', verbose_name='Элемент')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_permissions', to='articles.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Право доступа группы на элемент',
                'verbose_name_plural': 'Права доступа групп на элементы',
                'ordering': ['group__name', 'element__name'],
            },
        ),
        # Добавляем новое поле element в Article
        migrations.AddField(
            model_name='article',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.element', verbose_name='Элемент'),
        ),
        # Удаляем старые поля и модели
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='section',
        ),
        migrations.DeleteModel(
            name='CategoryPermission',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        # Добавляем индексы и constraints для новых моделей
        migrations.AddIndex(
            model_name='elementpermission',
            index=models.Index(fields=['group', 'element'], name='articles_el_group_i_024332_idx'),
        ),
        migrations.AddIndex(
            model_name='elementpermission',
            index=models.Index(fields=['element', 'permission_level'], name='articles_el_element_d6ef85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='elementpermission',
            unique_together={('group', 'element')},
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['technology', 'sort_order', 'name'], name='articles_el_technol_8bf6d6_idx'),
        ),
    ]
