# Generated by Django 5.0.1 on 2025-12-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_element_remove_category_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='system_permission_level',
            field=models.CharField(choices=[('none', 'Нет доступа'), ('read', 'Чтение'), ('edit', 'Редактирование')], default='none', max_length=10, verbose_name='Уровень доступа к системе'),
        ),
        migrations.DeleteModel(
            name='ElementPermission',
        ),
    ]
