# Generated by Django 5.0.1 on 2025-12-03 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_rename_title_to_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='model_name',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='model_name',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.CreateModel(
            name='ArticleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('html', models.TextField(verbose_name='HTML содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шаблон статьи',
                'verbose_name_plural': 'Шаблоны статей',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='articles_ar_name_ac7b3d_idx')],
            },
        ),
    ]
