# Generated by Django 5.0.1 on 2025-12-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='table_of_contents',
            field=models.JSONField(blank=True, default=list, verbose_name='Содержание'),
        ),
    ]
