# Generated by Django 5.0.1 on 2025-12-12 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_article_table_of_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='element',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='articles.technology', verbose_name='Технология')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['technology', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='articles.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.model', verbose_name='Модель'),
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['technology', 'sort_order', 'name'], name='articles_ca_technol_3f734a_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['category', 'sort_order', 'name'], name='articles_mo_categor_4359e0_idx'),
        ),
    ]
